server:
  port: 8446
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: ENC(idIWCdznEM3ggslDeTmLJw==)
    key-store-type: PKCS12
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  config:
    import: optional:file:.env[.properties]  # .env import
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  datasource:
<<<<<<< HEAD
    #url: jdbc:mysql://127.0.0.1:3306/shopdb?serverTimezone=Asia/Seoul
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/sshopdb?characterEncoding=utf8
=======
    #url: jdbc:mysql://127.0.0.1:7306/shopdb?serverTimezone=Asia/Seoul
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:log4jdbc:mysql://127.0.0.1:7306/shopdb?characterEncoding=utf8
>>>>>>> origin/minwoo
#    username: smuser
#    password: ENC(idIWCdznEM3ggslDeTmLJw==)
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ENC(idIWCdznEM3ggslDeTmLJw==)

mybatis:
  type-aliases-package: edu.sm.app.dto
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: info

# Application Config
# @Value("${}")
app:
  url:
<<<<<<< HEAD
    sse: https://192.168.1.4:8444/ #admin
    mainsse: https://192.168.1.4:8443/ #shop
    websocketurl: https://192.168.1.4:8443/ #shop
=======
    sse: https://192.168.1.7:8444/   # admin
    mainsse: https://192.168.1.7:8443/   #shop
    websocketurl: https://192.168.1.7:8443/  #shop
>>>>>>> origin/minwoo
  dir:
    imgsdir: file:///C:/test4/test4/imgs/     # 화면 출력 용
    uploadimgsdir: C:/test4/test4/imgs/    # 파일 Write 용
    logsdir: file:///C:/smspring/logs/     # 화면 출력 용
    logsdirRead: C:/smspring/logs/     # 화면 출력 용
  key:
    skey: ${MY_KEY}
    algo: PBEWithMD5AndDES
    wkey: ENC(UzWKYGJ+aTCk7OeZFEj7nCxzQEkETz/jHkcLOOT4Sh1xqjJlAXwb1lBnz3vTMltzuSyT6SQc1XlmowT6E0ICIYIKAxMhKWRIplUobmAYN0ClSGG+TkwAq0gaAkhdvwLkg9bL1gUYM54=)
    owkey: ENC(vIqd9CSeOJ2B+RNZB8q8uX2gqVeotK1BVjLTnpvApIu0QKfrK4PIS+zKhZuQbERZ)
