server:
  port: 8442
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: ENC(idIWCdznEM3ggslDeTmLJw==)
    key-store-type: PKCS12
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  messages:
    basename: message
    encoding: utf-8
    cache-duration: 10
    fallback-to-system-locale: false
  config:
    import: optional:file:.env[.properties]  # .env import
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  datasource:
    #url: jdbc:mysql://127.0.0.1:3306/shopdb?serverTimezone=Asia/Seoul
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/sshopdb?characterEncoding=utf8
#    username: smuser
#    password: ENC(idIWCdznEM3ggslDeTmLJw==)
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ENC(idIWCdznEM3ggslDeTmLJw==)

mybatis:
  type-aliases-package: edu.sm.app.dto
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: info

# Application Config
app:
  url:
    websocketurl: https://192.168.1.4:8443/
  dir:
    imgsdir: file:///C:/test4/test4/imgs/     # 화면 출력 용
    uploadimgsdir: C:/test4/test4/imgs/    # 파일 Write 용
    logsdir: file:///C:/test4/logs/     # 화면 출력 용
    logsdirRead: C:/test4/logs/     # 화면 출력 용
  key:
    skey: ${MY_KEY}
    kakao: ${KAKAO_APP_KEY}
    algo: PBEWithMD5AndDES
    wkey: ENC(UzWKYGJ+aTCk7OeZFEj7nCxzQEkETz/jHkcLOOT4Sh1xqjJlAXwb1lBnz3vTMltzuSyT6SQc1XlmowT6E0ICIYIKAxMhKWRIplUobmAYN0ClSGG+TkwAq0gaAkhdvwLkg9bL1gUYM54=)
